set1 = {9, 8, 7, 5, 1, 5, 4, 2, 3, 5, 7, 8}
# print(set1)
# nullDict = {}
# nullSet = set()
# print(type(nullSet))
# print(type(nullDict))
# set1.add(10)
# print(set1)
# print(nullSet)
# nullSet.add(100)
# set1.union(nullSet)
# print(set1)
# print(nullSet)
# nullSet.remove(100)
# print(nullSet)
# set1.pop()
# print(set1)
# set1.clear()
# print(set1)
set2 = {65, 55, 5, 4, 7}
print(set2)
print(set1)
print(set1.union(set2))
print(set1.intersection(set2))